server:
  port: 8090 # Port number

spring:
  application:
    name: legendary-video-library # Application name
  data:
    mongodb:
      uri: mongodb://library:library@localhost:27017/librarydb?authSource=librarydb # MongoDB connection string
  jackson:
    property-naming-strategy: SNAKE_CASE # insert snake_case in JSON
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer #org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 10
        delivery.timeout.ms: 300000 # 5 minutos
        request.timeout.ms: 20000
        max.block.ms: 60000
    consumer:
      group-id: video-consumer-group # VERIFICAR COMO PRODUZIR PARA O MESMO GRUPO
      auto-offset-reset: earliest
      enable-auto-commit: false  # Desativa o auto commit, O Kafka não confirmará mensagens automaticamente.
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: manual # Configura ACK manual, Permite confirmar as mensagens explicitamente.

log4j2:
  formatMsgNoLookups: true # Remove lookups from log messages vulnerability

jwt:
  secret-key: U2VjcmV0S2V5QFRlY25pY29FbUluZm9ybWF0aWNhU2VuYWMyMDI1
#  expiration-ms: 600000  # 5 min = 300000

