server:
  port: 8090 # Port number

spring:
  application:
    name: legendary-video-library # Application name
  data:
    mongodb:
      uri: mongodb://library:library@localhost:27017/librarydb?authSource=librarydb # MongoDB connection string
  jackson:
    property-naming-strategy: SNAKE_CASE # insert snake_case in JSON

log4j2:
  formatMsgNoLookups: true # Remove lookups from log messages vulnerability

jwt:
  secret-key: U2VjcmV0S2V5QFRlY25pY29FbUluZm9ybWF0aWNhU2VuYWMyMDI1
#  expiration-ms: 600000  # 5 min = 300000

